--변수에 null 값 저장 막기
--변수 이름 자료형 NOT NULL := 또는 DEFAULT값 또는 표현식

SET SERVEROUTPUT ON;
DECLARE
    V_DEPTNO NUMBER(2) NOT NULL := 10;
BEGIN
    DBMS_OUTPUT.PUT_LINE('V_DEPTNO : ' || V_DEPTNO);
END;
/

SET SERVEROUTPUT ON;
DECLARE
    V_DEPTNO NUMBER(2) NOT NULL DEFAULT 20;
BEGIN
    DBMS_OUTPUT.PUT_LINE('V_DEPTNO : ' || V_DEPTNO);
END;
/