CREATE TABLE "SPRING"."COM_CODE" 
   (	"MST_CODE" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"DET_CODE" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"MST_NM" VARCHAR2(600 BYTE), 
	"DET_NM" VARCHAR2(600 BYTE), 
	"SEQ" NUMBER(7,0), 
	"USE_YN" CHAR(1 BYTE), 
	"REG_DT" DATE DEFAULT SYSDATE, 
	"REG_ID" VARCHAR2(20 BYTE), 
	"MOD_ID" VARCHAR2(20 BYTE), 
	"MOD_DT" DATE DEFAULT SYSDATE, 
	 PRIMARY KEY ("MST_CODE", "DET_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "SPRING_TS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SPRING_TS" ;
  
  Insert into SPRING.COM_CODE (MST_CODE,DET_CODE,MST_NM,DET_NM,SEQ,USE_YN,REG_DT,REG_ID,MOD_ID,MOD_DT) values ('PC_BOARD_DIV','10','게시구분','공지사항',10,'1',to_date('22/05/31','RR/MM/DD'),'ADMIN','ADMIN',to_date('22/05/31','RR/MM/DD'));
Insert into SPRING.COM_CODE (MST_CODE,DET_CODE,MST_NM,DET_NM,SEQ,USE_YN,REG_DT,REG_ID,MOD_ID,MOD_DT) values ('PC_BOARD_DIV','20','게시구분','자유게시판',20,'1',to_date('22/05/31','RR/MM/DD'),'ADMIN','ADMIN',to_date('22/05/31','RR/MM/DD'));

SELECT *
FROM com_code;