
  CREATE TABLE "SPRING"."PC_BOARD" 
   (	"SEQ" NUMBER(7,0) NOT NULL ENABLE, 
	"TITLE" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"CONTENTS" CLOB, 
	"READ_CNT" NUMBER(7,0), 
	"DIV" VARCHAR2(2 BYTE), 
	"REG_DT" DATE DEFAULT SYSDATE, 
	"REG_ID" VARCHAR2(20 BYTE), 
	"MOD_DT" DATE DEFAULT SYSDATE, 
	"MOD_ID" VARCHAR2(20 BYTE), 
	 CONSTRAINT "PK_PC_BOARD" PRIMARY KEY ("SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("CONTENTS") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "SPRING"."PC_BOARD"."SEQ" IS '순번';
   COMMENT ON COLUMN "SPRING"."PC_BOARD"."TITLE" IS '제목';
   COMMENT ON COLUMN "SPRING"."PC_BOARD"."CONTENTS" IS '내용';
   COMMENT ON COLUMN "SPRING"."PC_BOARD"."READ_CNT" IS '조회수';
   COMMENT ON COLUMN "SPRING"."PC_BOARD"."DIV" IS '구분';
   COMMENT ON COLUMN "SPRING"."PC_BOARD"."REG_DT" IS '등록일';
   COMMENT ON COLUMN "SPRING"."PC_BOARD"."REG_ID" IS '등록자';
   COMMENT ON COLUMN "SPRING"."PC_BOARD"."MOD_DT" IS '수정일';
   COMMENT ON COLUMN "SPRING"."PC_BOARD"."MOD_ID" IS '수정자';
   COMMENT ON TABLE "SPRING"."PC_BOARD"  IS '게시판';

TRUNCATE TABLE PC_BOARD;
INSERT INTO PC_BOARD 
SELECT    rownum AS SEQ,
	 '제목_'||  lpad(rownum,7,'0') AS TITLE,
	 '내용_'||  lpad(rownum,7,'0') AS CONTENTS,
	 0,
     DECODE(MOD(ROWNUM,2),0,'10','20') AS DIV,  
	 (SYSDATE - ROWNUM/(60*60)) REG_DT,
     'ADMIN' REG_ID,
	 (SYSDATE - ROWNUM/(60*60)) MOD_DT,
     'ADMIN' MOD_ID
FROM DUAL T1
CONNECT BY level <=10000;

SELECT *
FROM pc_board;

SELECT t1.SEQ,
       t1.TITLE,
       t1.div,
       t2.det_nm
FROM pc_board t1, com_code t2
WHERE t1.div = t2.DET_CODE
AND t2.MST_CODE = 'PC_BOARD_DIV'
AND t1.div = 10;