--특정 언어에 맞춰서 날짜출력하기
--TO_CHAR(날짜데이터,'출력되길 원하는 문자형태','NLS_DATE_LANGUAGE=language)

SELECT SYSDATE,
       TO_CHAR(SYSDATE,'MM') AS "MM",
       TO_CHAR(SYSDATE,'MON','NLS_DATE_LANGUAGE=KOREAN') AS "KORAAN",
       TO_CHAR(SYSDATE,'MON','NLS_DATE_LANGUAGE=JAPANESE') AS "JAPANESE",
       TO_CHAR(SYSDATE,'MON','NLS_DATE_LANGUAGE=ENGLISH') AS "ENGLISH",
       TO_CHAR(SYSDATE,'MONTH','NLS_DATE_LANGUAGE=ENGLISH') AS "ENGLISH"
FROM dual
;

SELECT SYSDATE,
       TO_CHAR(SYSDATE,'DD') AS "MM",
       TO_CHAR(SYSDATE,'DAY','NLS_DATE_LANGUAGE=KOREAN') AS "KORAAN",
       TO_CHAR(SYSDATE,'DAY','NLS_DATE_LANGUAGE=JAPANESE') AS "JAPANESE",
       TO_CHAR(SYSDATE,'DAY','NLS_DATE_LANGUAGE=ENGLISH') AS "ENGLISH",
       TO_CHAR(SYSDATE,'DY','NLS_DATE_LANGUAGE=ENGLISH') AS "ENGLISH"
FROM dual
;