--TCL(Transaction Control Language : commit(확정),rollback(취소)

--CTAS로 DEPT_TCL생성
CREATE TABLE DEPT_TCL
AS
SELECT * FROM dept;

SELECT * FROM DEPT_TCL;

--dept_tcl DML작업
--INSERT
--UPDATE
--DELETE
--SELECT

INSERT INTO DEPT_TCL VALUES (50,'DATEBASE','SEOUL');
UPDATE DEPT_TCL SET LOC = 'BUSAN'
WHERE DEPTNO = 40;
DELETE FROM DEPT_TCL WHERE dname = 'RESEARCH';

--ROLLBACK : DML작업들이 취소되었는지 확인
--트랜잭션
ROLLBACK;