--이클립스에서 TABLE_UNIQUE99 테이블 가져오기
ALTER TABLE TABLE_UNIQUE99
	DROP
		UNIQUE (
			LOGIN_ID
		)
		CASCADE
		KEEP INDEX;

DROP INDEX UIX_TABLE_UNIQUE99;

/* 테이블_UNIQUE */
DROP TABLE TABLE_UNIQUE99 
	CASCADE CONSTRAINTS;

/* 테이블_UNIQUE */
CREATE TABLE TABLE_UNIQUE99 (
	LOGIN_ID VARCHAR2(20BYTE), /* 로그인_ID */
	LOGIN_PWD VARCHAR2(20) NOT NULL, /* 로그인_비번 */
	TEL VARCHAR2(20BYTE) /* 전화 */
);

COMMENT ON TABLE TABLE_UNIQUE99 IS '테이블_UNIQUE';

COMMENT ON COLUMN TABLE_UNIQUE99.LOGIN_ID IS '로그인_ID';

COMMENT ON COLUMN TABLE_UNIQUE99.LOGIN_PWD IS '로그인_비번';

COMMENT ON COLUMN TABLE_UNIQUE99.TEL IS '전화';

CREATE UNIQUE INDEX UIX_TABLE_UNIQUE99
	ON TABLE_UNIQUE99 (
		LOGIN_ID ASC
	);

ALTER TABLE TABLE_UNIQUE99
	ADD
		CONSTRAINT UK_TABLE_UNIQUE99
		UNIQUE (
			LOGIN_ID
		);
        
-----------------------------------------------------        
SELECT t1.owner,
       t1.constraint_name,
       t1.constraint_type,
       t1.table_name
FROM user_constraints t1 
WHERE t1.table_name IN('TABLE_UNIQUE2','TABLE_UNIQUE99');