--1 테이블 복사
CREATE TABLE deptseq
AS
SELECT * FROM dept
;

SELECT * FROM deptseq;

--2 시퀀스 생성
CREATE SEQUENCE seq_deptseq
INCREMENT BY 1
START WITH 1
MAXVALUE 99
MINVALUE 1
NOCYCLE
NOCACHE;

--3 데이터 삽입
INSERT INTO deptseq VALUES (SEQ_DEPTSEQ.NEXTVAL, 'DEATABASE', 'SEOUL');
INSERT INTO deptseq VALUES (SEQ_DEPTSEQ.NEXTVAL, 'WEB', 'BUSAN');
INSERT INTO deptseq VALUES (SEQ_DEPTSEQ.NEXTVAL, 'MOBILE', 'ILSAN');

SELECT * FROM deptseq;