--테이블에 데이터 삽입
SET SERVEROUTPUT ON;
DECLARE

BEGIN
    FOR i IN 1..10 LOOP
        INSERT INTO T_SEQ_TEST(name)
        VALUES (DBMS_RANDOM.STRING('A',10));
    END LOOP;
    
    COMMIT;
END;
/

SELECT * FROM T_SEQ_TEST;