CREATE TABLESPACE goodman
DATAFILE 'C:\APP\LG\PRODUCT\18.0.0\ORADATA\XE\goobman.DBF'
SIZE 300M AUTOEXTEND ON NEXT 3M;

ALTER SESSION SET "_oracle_script"=true;
CREATE USER pcwk
IDENTIFIED BY goodman
DEFAULT TABLESPACE goodman
TEMPORARY TABLESPACE temp ;

GRANT RESOURCE, CREATE SESSION, CREATE VIEW, CREATE SYNONYM TO pcwk; 

REVOKE RESOURCE, CREATE TABLE FROM good;
